config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  get '/users/:id/graphs/new', to: 'graphs#new', as: 'new_graph'
  post '/users/:id/graphs', to: 'graphs#create', as: 'graphs'
  resources :graphs, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graph.rb
# == Schema Information
#
# Table name: graphs
#
#  id         :bigint(8)        not null, primary key
#  graph_id   :text             not null
#  graph_name :text             not null
#  unit       :text             not null
#  graph_type :integer          not null
#  color      :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Graph < ApplicationRecord
  belongs_to :user

  enum graph_type: %i(int float)
  enum color: %i(shibafu momiji sora ichou ajisai kuro)

  validates :graph_id, uniqueness: { scope: %i(graph_id user_id) }
  validates :graph_id, :graph_name, :unit, :graph_type, :color, :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint(8)        not null, primary key
#  user_name  :string           not null
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :graphs
  validates :user_name, presence: true, uniqueness: { allow_blank: true }
  validates :token, presence: true

  before_save :encrypt_token

  def encrypt_token
    self.token = token_encoder.encrypt_and_sign(self.token)
  end

  def decrypt_token
    return '' if self.token.to_s.empty?

    token_encoder.decrypt_and_verify(self.token)
  end

  def token_encoder
    cipher = 'aes-256-cbc'
    secret = Rails.application.credentials.secret_key_base
    # Saltはもうちょっとひねろうか
    salt = Rails.application.secret_key_base
    key_len = ActiveSupport::MessageEncryptor.key_len(cipher)
    key = ActiveSupport::KeyGenerator.new(secret).generate_key(salt, key_len)
    ActiveSupport::MessageEncryptor.new(key, cipher: cipher)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def new
    user = User.find(params[:id])
    @graph = user.graphs.new
  end

  def create
    @graph = Graph.new(graph_params)
    if @graph.save!
      flash[:success] = 'Graph created!'
      redirect_to_owner(@graph)
    else
      render 'new'
    end

  end

  def show
    @graph = Graph.find(params[:id])
  end

  def destroy
    graph = Graph.find(params[:id])
    graph.destroy
    flash[:success] = 'Deleted!'
    redirect_to_owner(graph)
  end

  def edit
    @graph = Graph.find(params[:id])
  end

  def update
    @graph = Graph.find(params[:id])
    if @graph.update(graph_params)
      flash[:success] = 'Updated!'
      redirect_to_owner(@graph)
    else
      render 'edit'
    end
  end

  private

  def graph_params
    params.require(:graph).permit(:graph_id, :graph_name, :unit, :graph_type, :color, :user_id)
  end

  def redirect_to_owner(graph)
    redirect_to graph.user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.ransack(params[:q])
    @users = @search.result
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Success to create a new user!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Deleted!'
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :token)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
  def graph_color_class(color)
    case color
    when 'shibafu'
      'success'
    when 'momiji'
      'danger'
    when 'sora'
      'primary'
    when 'ichou'
      'warning'
    when 'ajisai'
      'info'
    when 'kuro'
      'dark'
    else
      'light'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphs/_form.html.slim
= simple_form_for @graph do |f|
  = f.input :graph_id, as: :string
  = f.input :graph_name, as: :string
  = f.input :unit, as: :string
  = f.input :graph_type, collection: Graph.graph_types.keys
  = f.input :color, collection: Graph.colors.keys
  = f.hidden_field :user_id
  = f.button :submit, class: 'btn btn-success'

app/views/graphs/edit.html.slim
h1
  = "Edit #{@graph.user.user_name}' Graph"

= render 'form'

app/views/graphs/new.html.slim
h1
  = "#{@graph.user.user_name}'s New Graph"

= render 'form'

app/views/graphs/show.html.slim
h1
  = link_to @graph.user.user_name, @graph.user
  = "' #{@graph.graph_name}"

img src="https://pixe.la/v1/users/#{@graph.user.user_name}/graphs/#{@graph.graph_id}"  alt="#{@graph.graph_name}"

app/views/layouts/application.html.slim
html
  head
    title Pixela Client
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      = link_to 'Pixela Client', root_path, class: 'btn btn-link'

      - flash.each do |message_type, message|
        .alert class="alert-#{message_type}"
          = message
      = yield

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.input :user_name
  = f.input :token, as: :password, input_html: { value: @user.decrypt_token }
  = f.input :show_token, as: :boolean, input_html: { checked: false }
  = f.button :submit, class: 'btn btn-success'

app/views/users/edit.html.slim
h1 Edit User

= render 'form'

app/views/users/index.html.slim
h1 Users List

= search_form_for @search do |f|
  .form-row.align-items-center
    .col-auto
      = f.label :Name, class: 'col-form-label col-sm-2'
    .col-auto
      = f.search_field :user_name_cont, class: 'form-control'
    .col-auto
      = f.button :submit, class: 'btn btn-primary'
        = :Search

= link_to 'Add New User', new_user_path, class: 'btn btn-success'
table.table
  thead
    tr
      td Name
      td
  tbody
    - @users.each do |user|
      tr
        td
          = link_to user.user_name, user, class: 'btn btn-link'
        td
          = link_to :Edit, edit_user_path(user), class: 'btn btn-info'
          = link_to :Destroy, user, method: :delete, class: 'btn btn-danger',
                  data: {confirm: '削除しますか？'}

app/views/users/new.html.slim
h1 New User

= render 'form'

app/views/users/show.html.slim
h1
  = @user.user_name

= link_to :Edit, edit_user_path(@user), class: 'btn btn-info'
= link_to :Destroy, @user, method: :delete, class: 'btn btn-danger',
        data: { confirm: '削除しますか？' }

h3 Graphs

= link_to 'New Graph', new_graph_path(@user), class: 'btn btn-success'

table.table
  thead
    tr
      td id
      td name
      td color
      td
  tbody
    - @user.graphs.each do |graph|
      tr
        td
          = link_to graph.graph_id, graph, class: 'btn btn-link'
        td
          = graph.graph_name
        td
          h4
            .badge class="badge-#{graph_color_class(graph.color)}"
              = graph.color
        td
          = link_to :Edit, edit_graph_path(graph), class: 'btn btn-info'
          = link_to :Delete, graph, method: :delete, class: 'btn btn-danger',
                  data: { confirm: '削除しますか？' }